/*
*/
--author jun.cui@hctrip.cn

SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- Table structure for BS_BEAN_MODIFY_LOG
-- ----------------------------
DROP TABLE IF EXISTS `IFD_DTODEF`;
CREATE TABLE `IFD_DTODEF` (
  `ID` int(12) NOT NULL AUTO_INCREMENT,
  `DTONM` varchar(200) DEFAULT NULL,
  `DTODRPT` varchar(200) DEFAULT NULL,
  `MEMO` varchar(500) DEFAULT NULL,
  `VERSION` int(10) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=100 DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `IFD_EXAMPLEDEF`;
CREATE TABLE `IFD_EXAMPLEDEF` (
  `ID` int(12) NOT NULL AUTO_INCREMENT,
  `ACTIVE` varchar(1) DEFAULT NULL,
  `CLSNM` varchar(200) DEFAULT NULL,
  `INFNM` varchar(100) DEFAULT NULL,
  `EXAMPLENM` varchar(200) DEFAULT NULL,
  `EXAMPLETYP` varchar(1) DEFAULT NULL,
  `MEMO` varchar(500) DEFAULT NULL,
  `VERSION` int(10) DEFAULT NULL,
  `CREATED_BY_ID` varchar(50) DEFAULT NULL,
  `CREATED_BY_CODE` varchar(100) DEFAULT NULL,
  `CREATED_BY` varchar(50) DEFAULT NULL,
  `CREATED_DATE` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `MODIFIED_BY_ID` varchar(50) DEFAULT NULL,
  `MODIFIED_BY_CODE` varchar(100) DEFAULT NULL,
  `MODIFIED_BY` varchar(50) DEFAULT NULL,
  `MODIFIED_DATE` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `IFD_EXPASSERT`;
CREATE TABLE `IFD_EXPASSERT` (
  `ID` int(12) NOT NULL AUTO_INCREMENT,
  `ACTIVE` varchar(1) DEFAULT NULL,
  `EXAMPLEDEF_ID` int(13) DEFAULT NULL,
  `SCRIPT` text,
  `VERSION` int(10) DEFAULT NULL,
  `CREATED_BY_ID` varchar(50) DEFAULT NULL,
  `CREATED_BY_CODE` varchar(100) DEFAULT NULL,
  `CREATED_BY` varchar(50) DEFAULT NULL,
  `CREATED_DATE` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `MODIFIED_BY_ID` varchar(50) DEFAULT NULL,
  `MODIFIED_BY_CODE` varchar(100) DEFAULT NULL,
  `MODIFIED_BY` varchar(50) DEFAULT NULL,
  `MODIFIED_DATE` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


DROP TABLE IF EXISTS `IFD_EXPINPUT`;
CREATE TABLE `IFD_EXPINPUT` (
  `ID` int(12) NOT NULL AUTO_INCREMENT,
  `EXAMPLEDEF_ID` int(13) DEFAULT NULL,
  `PARAMNM` int(15) DEFAULT NULL,
  `VALUE` text,
  `VERSION` int(10) DEFAULT NULL,
  `CREATED_BY_ID` varchar(50) DEFAULT NULL,
  `CREATED_BY_CODE` varchar(100) DEFAULT NULL,
  `CREATED_BY` varchar(50) DEFAULT NULL,
  `CREATED_DATE` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `MODIFIED_BY_ID` varchar(50) DEFAULT NULL,
  `MODIFIED_BY_CODE` varchar(100) DEFAULT NULL,
  `MODIFIED_BY` varchar(50) DEFAULT NULL,
  `MODIFIED_DATE` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


DROP TABLE IF EXISTS `IFD_EXPOUTPUT`;
CREATE TABLE `IFD_EXPOUTPUT` (
  `ID` int(12) NOT NULL AUTO_INCREMENT,
  `EXAMPLEDEF_ID` int(13) DEFAULT NULL,
  `RETURNVALUE` text,
  `VERSION` int(10) DEFAULT NULL,
  `CREATED_BY_ID` varchar(50) DEFAULT NULL,
  `CREATED_BY_CODE` varchar(100) DEFAULT NULL,
  `CREATED_BY` varchar(50) DEFAULT NULL,
  `CREATED_DATE` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `MODIFIED_BY_ID` varchar(50) DEFAULT NULL,
  `MODIFIED_BY_CODE` varchar(100) DEFAULT NULL,
  `MODIFIED_BY` varchar(50) DEFAULT NULL,
  `MODIFIED_DATE` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `IFD_INFPARAM`;
CREATE TABLE `IFD_INFPARAM` (
  `ID` int(12) NOT NULL AUTO_INCREMENT,
  `CLSNM` varchar(200) DEFAULT NULL,
  `INFNM` varchar(100) DEFAULT NULL,
  `PARAMNM` varchar(100) DEFAULT NULL,
  `PARAMDRPT` varchar(200) DEFAULT NULL,
  `PARAMTYP` varchar(50) DEFAULT NULL,
  `LEN` smallint(2) DEFAULT NULL,
  `PRECISION` smallint(1) DEFAULT NULL,
  `DTONM` varchar(200) DEFAULT NULL,
  `SEQ` varchar(1) DEFAULT NULL,
  `MEMO` varchar(500) DEFAULT NULL,
  `VERSION` int(10) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


DROP TABLE IF EXISTS `IFD_INTERFACEDEF`;
CREATE TABLE `IFD_INTERFACEDEF` (
  `ID` int(12) NOT NULL AUTO_INCREMENT,
  `ACTIVE` varchar(1) DEFAULT NULL,
  `CLSNM` varchar(200) DEFAULT NULL,
  `INFNM` varchar(100) DEFAULT NULL,
  `INFDRPT` varchar(200) DEFAULT NULL,
  `INFURL` varchar(200) DEFAULT NULL,
  `INFMETHOD` varchar(20) DEFAULT NULL,
  `INFTYP` varchar(20) DEFAULT NULL,
  `RETURNDTONM` varchar(200) DEFAULT NULL,
  `MEMO` varchar(500) DEFAULT NULL,
  `VERSION` int(10) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `IND_DTOFIELD`;
CREATE TABLE `IND_DTOFIELD` (
  `ID` int(12) NOT NULL AUTO_INCREMENT,
  `DTONM` varchar(200) DEFAULT NULL,
  `FIELDNM` varchar(100) DEFAULT NULL,
  `FIELDDRPT` varchar(200) DEFAULT NULL,
  `FIELDTYP` varchar(50) DEFAULT NULL,
  `LEN` smallint(2) DEFAULT NULL,
  `PRECISION` smallint(1) DEFAULT NULL,
  `REFDTONM` varchar(200) DEFAULT NULL,
  `SEQ` varchar(1) DEFAULT NULL,
  `MENO` varchar(500) DEFAULT NULL,
  `VERSION` int(10) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
